sudo: false

language: php

notifications:
  email:
    on_success: never
    on_failure: change
  slack:
    rooms:
      secure: udkCF6hl4lLrlhXqUq26TuKGKRzT/+q2e3Wg7nvEvlTlrBXFrJU0aJmBM3UehAo3HZRhzhK11nUoZBmndZWKSefCys7Fpe0Km/V2zpa7VDWjUMnx1OMRsTu5C64q4qg2xTUnQqnsmjXYKcZT1jH4HbFEdYtOnu9ajIHZWuNiYtua48lVTC0z15zpn2ZdsnhCmsT7bCxqGmknk9xHXZaZjR4MwkUDosP/TDGmHhrto3tveKmVB76Ax0rzUo0WrlDjZTauS1FRQBxotDwJLwo7eE6XftQKeDIiNM7acGfioGRKij+xoedUSnRxa54Pc/ILE7p+km/dcjYPJMnvE9KaKgVo/yRbsxLVQQht0kw9020KtvJ83ETCGO1tYixHXq8dwpLAi1ajOucfusWgDVa8Yqg82Z7Wefq4yWsArpQxMs1bsqq0aARdvOYx1vukhiGqp3D0jYYaiFJ7lFzKOz7CGEkh1I9jhL2m1/zOkD06Ei8RPi3BYd0W4iyP506qZz2frO5Jxqhsdgj+wCkikxLxVNTLf5wvpVWwGUq4fOS4u8yFFyamfBS9zzM04IVo1SdU3gbBlIAYX1VLyq2hoCs26ai9NkSZVtEH+gkx0N9800D23kvE9sTPGQNwOk0+h/qiFteKXVsQCKg47FN1y8NIZg/q5knL0yQQegzFe9jx5H8=

branches:
  only:
    - /^v\d.*$/
    - master
    - develop

php:
  - 5.6
  - 7.1

env:
  - WP_VERSION=4.4 WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=trunk WP_MULTISITE=0

matrix:
  fast_finish: true
  exclude:
    - php: 7.1
      env: WP_VERSION=4.4 WP_MULTISITE=0

install:
  - export DEV_LIB_PATH=bin/dev-lib
  - export DEV_LIB_SKIP=codeception,jscs,jshint,yuicompressor,phpunit,xmllint
  - if [ ! -e "$DEV_LIB_PATH" ] && [ -L .travis.yml ]; then export DEV_LIB_PATH=$( dirname $( readlink .travis.yml ) ); fi
  - if [ ! -e "$DEV_LIB_PATH" ]; then git clone https://github.com/xwp/wp-dev-lib.git $DEV_LIB_PATH; fi
  - source $DEV_LIB_PATH/travis.install.sh

script:
  - source $DEV_LIB_PATH/travis.script.sh

after_script:
  - source $DEV_LIB_PATH/travis.after_script.sh

before_deploy:
  - npm install
  # Regenerate our documentation to include any new actions/filters
  - grunt docs
  # Build the plugin for deployment
  - grunt build

deploy:
  provider: releases
  api_key:
    secure: tri05kis6yFjI4Cwh5Y36JDoPkX9GsnvGbFwpBs5LXHCRod2x23IqqkavcM4zvDR5Hp/GXiRqTh5hi/GpsqLaBmBcoFf8LzfN8Wt4xIMU2fxch0KNTtKSH9tcb7uuzUzFn/L4348CnrZ9aRIVYUwXVra6sRCX4P5rkVysLxVu7SoEtxbA82ZHstF3M68k3AwPu2pEg0khrCtuy1OI32y6yiravelfoCKfFY6tbjSsJ4oywIuFau+yaYqyBTep6IjTmccKQ+9uPKLHrFItT138mTIfG3mc6R3BYPmxrWkKxWphM7iB6tOppRUi7azsN0CxKNvhmlIR4HRRm8uqp0RJGOOXURlGNyAMNy/Qh14JIFrfxIQde4b/QjKVgnbOyhCRphhGIc1qHf4r5+gjzWkkm999XadVmCNYVAft+pX52KtBVGCSkg+QkjTWmQon2UUuL3h6XVSW41/FwMCQK4oSRtIjmekUAIpzP1icTbfknsnj1AW/s9HkngCsBLkGtRynxcLNzyokQsZjkDm0g8vd7OW9RdeXzKZiBVVKymHumJkMu6AMbBefurf1fu5iaxfymqwPu5JrffIJrLvSncyomSIl5+X9qMZFtG1Eeob7CtPi8crUgFVgbBEV/lYsXQa24AaWFk49P/N2WCMxOVeHwf5OyVEnnG5TgN6onFQR+A=
  file_glob: true
  file: timeline-express-single-column-add-on-*.zip
  on:
    tags: true
    repo: CodeParrots/timeline-express-single-column-add-on
    php: '7.1'
    condition: "$WP_VERSION=trunk"
  skip_cleanup: true
  overwrite: true
