sudo: false

language: php

notifications:
  email:
    on_success: never
    on_failure: change
  slack:
    rooms:
      secure: pvGn8xlBidN8Bhc806gOs4bE3/gcL5VdH9W4LaTf9IBdFjLSenrXHIxEY/opD+/OMvY2p/LJF5Gd2ish+3sAl58xHe4OR8GPBVV7JLMkhbZhYbCWIfJrkeDiqgkv97TKwW674ei1SPDRLP9vtHf0XxFyOyADjVZWEGKyNecueviNB8/IMR/QgsqntXnjANOMm08A69/VS0+XDswD8cAAfSj8O4imB+DVRkFrFYDI0HuLAjYsGq7WKL+Vh1x1+iTGdSVfNJ5yi0wr8v40DpMG/rzaf3jfymI4m/dqhOUpofMZdm0+Iqdu+GzvJ7bX7q4nD7gz0i+e75ha3a75et8YC+Ri6E6oBZOfAu36aCstTQ0Nza+Ejut1+ozq2TlXEKH+mSIArQYt8LVaRgC5NfnzwvQ4+wDliyoEDSw+h2bgtaEyrPtua6PzoL4uHbye8ngDOq2Nibc+wlE74ehz6AuxjCyPUuFfD65zR0zsEsdSGqLmse7ErLhNInyjDAqij5oWqCWRlXA1FxoKiEoFj0siLCP8guKhskt5gN0ykPnivG405FrMeHE3z2XJw+uDUVP2aDHgz9fqVK31rdHDyC/8Y6cY/yILGbo4Hh3+cZEvann4sMBhaPPaZpjchuAaoatjt2CwrNgQlCwnsNSmKD3ivWfN2iOPX+Eho3zjQSN6hkY=

branches:
  only:
    - /^v\d.*$/
    - master
    - develop

php:
  - 5.6
  - 7.1

env:
  - WP_VERSION=4.4 WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=trunk WP_MULTISITE=0

matrix:
  fast_finish: true
  exclude:
    - php: 7.1
      env: WP_VERSION=4.4 WP_MULTISITE=0

install:
  - export DEV_LIB_PATH=bin/dev-lib
  - export DEV_LIB_SKIP=codeception,jscs,jshint,yuicompressor,phpunit,xmllint
  - if [ ! -e "$DEV_LIB_PATH" ] && [ -L .travis.yml ]; then export DEV_LIB_PATH=$( dirname $( readlink .travis.yml ) ); fi
  - if [ ! -e "$DEV_LIB_PATH" ]; then git clone https://github.com/xwp/wp-dev-lib.git $DEV_LIB_PATH; fi
  - source $DEV_LIB_PATH/travis.install.sh

script:
  - source $DEV_LIB_PATH/travis.script.sh

after_script:
  - source $DEV_LIB_PATH/travis.after_script.sh

before_deploy:
  - npm install
  # Regenerate our documentation to include any new actions/filters
  - grunt docs
  # Build the plugin for deployment
  - grunt build

deploy:
  provider: releases
  api_key:
    secure: tri05kis6yFjI4Cwh5Y36JDoPkX9GsnvGbFwpBs5LXHCRod2x23IqqkavcM4zvDR5Hp/GXiRqTh5hi/GpsqLaBmBcoFf8LzfN8Wt4xIMU2fxch0KNTtKSH9tcb7uuzUzFn/L4348CnrZ9aRIVYUwXVra6sRCX4P5rkVysLxVu7SoEtxbA82ZHstF3M68k3AwPu2pEg0khrCtuy1OI32y6yiravelfoCKfFY6tbjSsJ4oywIuFau+yaYqyBTep6IjTmccKQ+9uPKLHrFItT138mTIfG3mc6R3BYPmxrWkKxWphM7iB6tOppRUi7azsN0CxKNvhmlIR4HRRm8uqp0RJGOOXURlGNyAMNy/Qh14JIFrfxIQde4b/QjKVgnbOyhCRphhGIc1qHf4r5+gjzWkkm999XadVmCNYVAft+pX52KtBVGCSkg+QkjTWmQon2UUuL3h6XVSW41/FwMCQK4oSRtIjmekUAIpzP1icTbfknsnj1AW/s9HkngCsBLkGtRynxcLNzyokQsZjkDm0g8vd7OW9RdeXzKZiBVVKymHumJkMu6AMbBefurf1fu5iaxfymqwPu5JrffIJrLvSncyomSIl5+X9qMZFtG1Eeob7CtPi8crUgFVgbBEV/lYsXQa24AaWFk49P/N2WCMxOVeHwf5OyVEnnG5TgN6onFQR+A=
  file_glob: true
  file: timeline-express-single-column-add-on-*.zip
  on:
    tags: true
    repo: CodeParrots/timeline-express-single-column-add-on
    php: '7.1'
    condition: "$WP_VERSION=trunk"
  skip_cleanup: true
  overwrite: true
