sudo: false

language: php

notifications:
  email:
    on_success: never
    on_failure: change
  slack:
    rooms:
      secure: gAMR6q8nbEU6QmVt4OTDHYLn3ciCCevUD46uJZehlVMb0D5WwQcJMsa9V/oP5ebZIhXtXrRw0r57MGX/y1vPEABSHS/v0i49gtRajOybmMfqzATa8uFqUIuFDuvMKK6Ys3kmvGp7y0Zn+FeeBfH2II+THp20PbGDsrHxvmgNf3f9II3PRh2BtrtAETBoIyclYaarvI+1ZsykqOhAyYH6F9/+i3lRgZxyM6NWwblG2locLt+dP8592hmwaBoYvnYIKHtM+B231l/JLMbcdWnQbcSLqCOwH6nr1s0jxBEnAcKRgYQKLEh23Hn0m5TA4s4w08tKle3aoWz/5LmeQSF8dd5YWBgVuFemH3aDYiD2JXq7hMFLdtkDf16IAByW5QqvwCV8eCz+3nogEN5AkHQISxAxAkjfC2bGcVnTfo6mkwi+PB7EIngowmpdz3FdmsuImAptB9lpRyV8PEbWgqbWx0C9PXJROjHE+WU0jjnY7wu+4SxwPCEjV60A1sqvQG5wCyJ+5QdwSTagZdBpH/lqr+R8pd58kkgX7uq9+5u2xySWO6dqHZWbOVt50bB+5Y0gQR5I2Zr+al7T4qt5AsxtWofXrxjxgKEuV4pDPUEtqh5v9c93Adli0lQWBpOS/b1o5rd6iRx6lvJRBGu+5KGvSfABt545LqgGV9y6txAfFZw=

branches:
  only:
    - /^v\d.*$/
    - master
    - develop

php:
  - 5.6
  - 7.1

env:
  - WP_VERSION=4.4 WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=trunk WP_MULTISITE=0

matrix:
  fast_finish: true
  exclude:
    - php: 7.1
      env: WP_VERSION=4.4 WP_MULTISITE=0

install:
  - export DEV_LIB_PATH=bin/dev-lib
  - export DEV_LIB_SKIP=codeception,jscs,jshint,yuicompressor,phpunit,xmllint
  - if [ ! -e "$DEV_LIB_PATH" ] && [ -L .travis.yml ]; then export DEV_LIB_PATH=$( dirname $( readlink .travis.yml ) ); fi
  - if [ ! -e "$DEV_LIB_PATH" ]; then git clone https://github.com/xwp/wp-dev-lib.git $DEV_LIB_PATH; fi
  - source $DEV_LIB_PATH/travis.install.sh

script:
  - source $DEV_LIB_PATH/travis.script.sh

after_script:
  - source $DEV_LIB_PATH/travis.after_script.sh

before_deploy:
  - npm install
  # Regenerate our documentation to include any new actions/filters
  - grunt docs
  # Build the plugin for deployment
  - grunt build

deploy:
  provider: releases
  api_key:
    secure: tri05kis6yFjI4Cwh5Y36JDoPkX9GsnvGbFwpBs5LXHCRod2x23IqqkavcM4zvDR5Hp/GXiRqTh5hi/GpsqLaBmBcoFf8LzfN8Wt4xIMU2fxch0KNTtKSH9tcb7uuzUzFn/L4348CnrZ9aRIVYUwXVra6sRCX4P5rkVysLxVu7SoEtxbA82ZHstF3M68k3AwPu2pEg0khrCtuy1OI32y6yiravelfoCKfFY6tbjSsJ4oywIuFau+yaYqyBTep6IjTmccKQ+9uPKLHrFItT138mTIfG3mc6R3BYPmxrWkKxWphM7iB6tOppRUi7azsN0CxKNvhmlIR4HRRm8uqp0RJGOOXURlGNyAMNy/Qh14JIFrfxIQde4b/QjKVgnbOyhCRphhGIc1qHf4r5+gjzWkkm999XadVmCNYVAft+pX52KtBVGCSkg+QkjTWmQon2UUuL3h6XVSW41/FwMCQK4oSRtIjmekUAIpzP1icTbfknsnj1AW/s9HkngCsBLkGtRynxcLNzyokQsZjkDm0g8vd7OW9RdeXzKZiBVVKymHumJkMu6AMbBefurf1fu5iaxfymqwPu5JrffIJrLvSncyomSIl5+X9qMZFtG1Eeob7CtPi8crUgFVgbBEV/lYsXQa24AaWFk49P/N2WCMxOVeHwf5OyVEnnG5TgN6onFQR+A=
  file_glob: true
  file: timeline-express-single-column-add-on-*.zip
  on:
    tags: true
    repo: CodeParrots/timeline-express-single-column-add-on
    php: '7.1'
    condition: "$WP_VERSION=trunk"
  skip_cleanup: true
  overwrite: true
